name: 💡 功能请求 (Feature Request)
about: 建议新功能或改进现有功能。

labels:
  - enhancement
  - needs triage

body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间提出宝贵的建议，帮助我们改进项目！

        一个好的功能请求应该清晰地说明它要解决的问题和它带来的价值。

  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 请清晰、简洁地描述您希望添加或改进的功能。
      placeholder: 例如：我希望在用户个人资料页面添加一个“导出数据”的按钮。
      render: markdown
    validations:
      required: true

  - type: textarea
    id: problem-and-motivation
    attributes:
      label: 问题与动机
      description: 这个新功能旨在解决什么痛点？为什么它对用户很重要？
      placeholder: 例如：目前用户无法备份他们的数据，如果他们想迁移到其他服务会非常不便，这降低了用户的安全感和控制权。
      render: markdown
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案 (可选)
      description: 如果您对如何实现有任何想法，请在这里分享。例如：API 设计、UI/UX 草图、伪代码等。
      placeholder: |
        例如：
        1. 在个人资料页面右上角添加一个“导出”按钮。
        2. 点击后，向后端 /api/v1/users/me/export 发起一个 POST 请求。
        3. 后端生成一个包含用户所有数据的 JSON 文件，并开始下载。
      render: markdown

  - type: textarea
    id: alternatives
    attributes:
      label: 考虑过的替代方案 (可选)
      description: 您是否考虑过其他实现方式或替代方案？为什么当前建议是最好的？
      render: markdown

  - type: textarea
    id: additional-context
    attributes:
      label: 其他上下文信息 (可选)
      description: 任何其他有助于我们理解您建议的信息，例如相关项目的链接、截图或设计稿。

  - type: checkboxes
    id: confirmation
    attributes:
      label: 确认事项
      description: 在提交之前，请确认您已完成以下操作。
      options:
        - label: 我已在现有的 Issues 中搜索，没有发现重复的功能请求。
          required: true
        - label: 我已阅读并理解了项目的贡献指南 (CONTRIBUTING.md)。
          required: false # 设为可选，因为并非所有项目都有此文件